version: '2.1'

services:
  eureka-server:
    build: 
      context: ./eureka
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8761
      - SPRING_APPLICATION_NAME=eureka-server
    expose: 
      - 8761
    ports: 
      - 8761:8761
    networks: 
      - microservices-demo 

  product-service:
    build: 
      context: ./product
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8081
      - SPRING_APPLICATION_NAME=product-service
      - EUREKA_SERVICE_URL=http://eureka-server:8761/eureka
      - MONGODB_URI=mongodb://admin:Welcome%40123%23@mongo-db-demo:27017/product?authSource=admin&authMechanism=SCRAM-SHA-1
    expose: 
      - 8081
    ports: 
      - 8081:8081
    depends_on:
      - mongo-db-demo
      - eureka-server
    networks: 
      - microservices-demo  

  mongo-db-demo:
    image: mongo:latest
    expose:
      - 27017
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Welcome@123#
    volumes:
      - ~/db/mongo:/data/db
    networks: 
      - microservices-demo

networks:
  microservices-demo:
    driver: bridge